In [1]:
from text_gan.layers import CAZ_Q_Encoder
from text_gan.data.qgen_ca_q import CA_QPair, CA_Qcfg
import tensorflow as tf
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        tf.config.experimental.set_memory_growth(gpus[0], True)
    except RuntimeError as e:
        print(e)

In [2]:
data = CA_QPair.load()
train = data.train

In [3]:
train = train.skip(1).take(1).batch(1)

In [4]:
import numpy as np

In [5]:
word_emb_mat = np.load(CA_Qcfg.CIDX2EMB)

In [6]:
word_emb_mat.shape

(44790, 300)

In [7]:
enc = CAZ_Q_Encoder(word_emb_mat)

In [8]:
d = next(train.as_numpy_iterator())
d

((array([[   12,  2298,     9,     4,   600,  1555,    21,     4,   407,
              6, 13284,     1,    14,     4,  1294,    20,    54,  3676,
             24,  8845,  1248,    21,     4,   168,    35,   820,  3776,
           7613,     7,   195, 12102,   389,     4,   933,     5, 14926,
          12587,  8845,  6141, 15859,     7,   195,   524,  5360,     4,
           2723,  5246,    21,    89,  2843,    27,  6770,  9453, 12587,
              7,    31,    68,  1402,   118,     4,  2723,  1921,   399,
            187,     9,   126,   571,     5,    15,     9,  2809,  9351,
              5,     4,   802,   889,  5246,    88,  1198,  7613,     5,
             46,    15,  4256,  7613,    32,    33,  9468,    24,    22,
             97,  3776,     8,  5876,  1373,    35,    28,  6249,  7613,
              7,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,

In [9]:
op = enc((d[0][0], d[0][1]))

In [11]:
op

(<tf.Tensor: shape=(1, 32), dtype=float32, numpy=
 array([[-0.5832698 ,  0.2967689 , -0.7805909 , -0.1571089 ,  0.14838737,
          0.4844766 , -0.00615954,  0.38270152, -0.08904511, -0.17057121,
          0.66873455,  0.39930263, -0.31490922, -0.476024  ,  0.6688216 ,
         -0.7600732 ,  0.48992154, -0.2133846 , -0.49736843, -0.31560126,
          0.02557979,  0.14044312,  0.7104269 , -0.62986094, -0.8340663 ,
          0.7926929 ,  0.10278066,  0.7726338 , -0.48687574,  0.7227173 ,
          0.3417062 , -0.4191574 ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 250, 32), dtype=float32, numpy=
 array([[[-0.14962393,  0.13419496, -0.14588042, ...,  0.3491785 ,
           0.06447344, -0.01453531],
         [-0.20715842,  0.17900138, -0.1949864 , ...,  0.28637484,
           0.0055774 , -0.06525897],
         [-0.11661983,  0.18770188, -0.18350747, ...,  0.19868684,
          -0.01845869, -0.1351095 ],
         ...,
         [ 0.35696   ,  0.00646537,  0.2586289 , ...,  0.3115636 ,
    

In [17]:
tf.nn.softmax([1.0,2.0,1.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.21194157, 0.5761169 , 0.21194157], dtype=float32)>